typelevel/sbt-tpolecat

.travis.yml
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

"-Wunused:imports" was missing and "-Wunused:implicits" was duplicate.

Change duplicated "-Wunused:implicits" to "-Wunused:imports"

---

build.sbt

So [Scala Steward](https://github.com/fthomas/scala-steward) and [Scaladex](https://index.scala-lang.org/) can know the home of the published artifact.

Add homepage/SCM info

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

"Ensure that a `@nowarn` annotation actually suppresses a warning."

Add -Wunused:nowarn to 2.13 builds.

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

I currently see this when I compile:
```
sbt:pstor-root> test:compile
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Compiling 1 Scala source to /Users/david/workspace/pstor-compute/server/target/scala-2.13/classes ...
[info] Compiling 5 Scala sources to /Users/david/workspace/pstor-compute/index-builder/target/scala-2.13/classes ...
[error] 'nowarn' is not a valid choice for '-Wunused'
[error] 'nowarn' is not a valid choice for '-Wunused'
```
So here's a PR to remove `nowarn` for 2.13 and introduce explicits to address https://github.com/DavidGregory084/sbt-tpolecat/issues/18
Thanks for the plugin

explicits && nowarn

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

Without it, unused local and private vals, vars, defs and types are not reported.
Next versions of Scala have a more fine grained control.
References:
* https://scalacenter.github.io/scalafix/docs/rules/RemoveUnused.html
* https://www.threatstack.com/blog/useful-scalac-options-for-better-scala-development-part-1
* https://www.thetopsites.net/article/50159717.shtml

Add `-Ywarn-unused` for Scala 2.11

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/test/scala/io/github/davidgregory084/TpolecatPluginSuite.scala

- Adds support for options added in patch versions
- Adds `-Xlint:strict-unsealed-patmat` option for scala versions >= 2.13.4 and <= 3.0.0

Scala 2.13.4 support

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

Remove byname-implicit lint option

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

Follow-up to #32 to fix a bug where `String`s and `Int`s were being compared in the pattern guard causing the case handling patch versions to never match.

Fix patch version logic

---

README.md
build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt

- Add support for Scala 2.13.5
- Update SBT to 1.4.7
- Update MUnit to 0.7.22
- Update SBT Header to 5.6.0
- Update SBT CI Release 1.5.5
Thank you so much for your work on this plugin!

Updates to support Scala 2.13.5

---

README.md
build.sbt
project/build.properties
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/sbt-test/sbt-tpolecat/scalacOptions/project/plugins.sbt

- add -Vimplicits and -Vtype-diffs for Scala 2.13.6
- drop support for very old dotty versions
- drop support for SBT 0.13.x
- No longer require the sbt-dotty plugin
Thanks to @githubmo for helping me deal with the version accuracy

Update project for Scala 3.0.0 and Scala 2.13.6

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

Add -source future, strictEquality

---

.github/workflows/ci.yml
README.md
build.sbt
project/build.properties
project/plugins.sbt
project/project/plugins.sbt
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/test/scala/io/github/davidgregory084/TpolecatPluginSuite.scala

This updates a few different things:
* Drops 2.10.x support - it appears that 2.10.x cannot be used with Java 17
* Drops old minor releases for each major 2.x release from scripted testing
* Adds Scala 3.1.x to scripted testing
* Adds Java 17 (the new LTS) to the build matrix
* Clarifies that the Scala Code of Conduct applies here
* Updates various test & sbt plugin dependencies which have seen new releases

Various dependency & README updates

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

Resolves #46. This linting flag warns users when their @implicitNotFound or @implicitAmbiguous annotation references an unbound type parameter. It seems to have been added in the 2.13 RC period.

Add implicitNotFound / implicitAmbiguous linting flag

---

.scalafix.conf
.scalafmt.conf
README.md
build.sbt
project/plugins.sbt
src/main/scala/io/github/davidgregory084/OptionsMode.scala
src/main/scala/io/github/davidgregory084/ScalaVersion.scala
src/main/scala/io/github/davidgregory084/ScalacOption.scala
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/sbt-test/sbt-tpolecat/scalacOptions/project/build.properties
src/sbt-test/sbt-tpolecat/scalacOptions/project/build.sbt
src/sbt-test/sbt-tpolecat/scalacOptions/test
src/test/scala/io/github/davidgregory084/TpolecatPluginSuite.scala

This adds a concept of modes and some default option sets to the plugin.
`DevMode` - this mode uses `ScalacOptions.default`, an always-on set of options
`CiMode` - this mode uses the dev mode options plus `ScalacOption.fatalWarningOptions`
`ReleaseMode` - this mode uses the CI mode options plus `-opt:l:method` method-local optimisation by default
Inlining can be enabled by using `ScalacOptions.optimizerOptions` with the packages to inline from e.g. `ScalacOptions.optimizerOptions("scala.**")` to inline from scala packages or `ScalacOptions.optimizerOptions("**")` to inline from everywhere.
It adds command aliases to enable each mode
`tpolecatDevMode` - sets the mode to `DevMode`
`tpolecatCiMode` - sets the mode to `CiMode`
`tpolecatReleaseMode` - sets the mode to `ReleaseMode`
These modes …

Add dev, CI, release mode functionality to the plugin

---

README.md

Expand a bit on the use of `scalacOptions` and the options keys of this plugin.

Expand usage instructions

---

README.md
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt

I have noticed that many users filter out `-Xfatal-warnings` explicitly - this means that the approach used in 0.2.0 of enabling `-Werror` for >= 2.13 < 3.0.0 does not work well for them as `-Werror` does not get filtered out.

Make -Xfatal-warnings a universal option again

---

src/main/scala/io/github/davidgregory084/ScalacOption.scala
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

This fixes a problem I noticed in outwatch/outwatch#599:
If we don't declare `scalacOptions` as a derived setting, then manipulating `tpolecatScalacOptions` in other dependency configurations doesn't work.
This means that (for example), modifying `Test / tpolecatScalacOptions` to filter out fatal warnings does not affect the resulting `Test / scalacOptions` as they are only based on `Compile / scalacOptions`.
Likewise, for other settings that are usually used while scoped to a particular dependency configuration, if we don't make those into derived settings then they won't react to changes in their scoped dependencies either.

Make settings with dependencies into derived settings

---

src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala

Fix #60 when scalac options specified in ThisBuild scope by user are ignored

---

build.sbt
src/main/scala/io/github/davidgregory084/ScalaVersion.scala
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt

Adds -Xsource and -source options to the DSL.
`source3` only exists in the DSL for Scala 2.x since `-source 3` is default for Scala 3.x.

Add -Xsource and -source options to the ScalacOptions DSL.

---

.gitignore
README.md
build.sbt
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/sbt-test/sbt-tpolecat/scalacOptions/test

#61 broke filtering of console `scalacOptions`
This is fixed with the help of a new setting key `tpolecatExcludeOptions` that is used to filter out all options and not just the current additions. 
Also, this PR adds tests to `console`, `ThisProject` and `ThisBuild` direct usages of `scalacOptions`

Fix addition of unwanted options to console task

---

README.md
build.sbt
src/main/scala/io/github/davidgregory084/ScalaVersion.scala
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt

I moved away from 2.11 so long ago that I didn't even know it had a SI-2712 backport!

Extremely belatedly drop sbt-partial-unification dependency

---

src/main/scala/io/github/davidgregory084/ScalaVersion.scala
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/sbt-test/sbt-tpolecat/scalacOptions/test

... and use them to test a fix for #74.
Unfortunately this means letting go of the fix for #60  - we can no longer support users appending to `ThisBuild / scalacOptions`. I believe that appending to `ThisBuild / tpolecatScalacOptions` would work though.

Add -Ybackend-parallelism and -release

---

.github/workflows/ci.yml
.github/workflows/release.yml
src/main/scala/io/github/davidgregory084/JavaMajorVersion.scala
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt

This should filter out the release option whenever it's not possible for it to be applied.
Also switched from setup-scala to setup-java, which should resolve #77.

Add Java runtime version check to release option

---

build.sbt
src/main/scala/io/github/davidgregory084/ScalacOption.scala
src/main/scala/io/github/davidgregory084/ScalacOptions.scala
src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
src/test/scala/io/github/davidgregory084/TpolecatPluginSuite.scala

I'm going to use this PR to batch up some breakage for 0.4
* Most importantly - changes `ScalacOptions` to be `private[davidgregory084]` to avoid bincompat concerns with changing it in future. Interestingly if you change something to be `private[somepackage]` in your latest commit the MiMa warnings go away, even though your changes are still binary incompatible with the previous release.
* Changes `ScalacOption` from a container of `tokens: List[String]` to `option: String` and `args: List[String]`. Equality is determined only by `option`. I think this makes more sense for users when filtering options, since when filtering an option users probably don't really care which arguments have been provided for that option.
* Adds `ScalacOptions.other`. This fixes #65 by providing an escape hatch …

The binary breaking bonanza

---

src/main/scala/io/github/davidgregory084/ScalacOptions.scala

As a user, I would like to define the following option in a consistent way: `-Xmax-classfile-name 100` with
```scala
ScalacOptions.advancedOption(
"max-classfile-name",
List("100"),
version => version.isBetween(V2_12_0, V2_13_0)
)
```

Add advancedOption API with arguments support

---

plugin/src/main/scala/io/github/davidgregory084/ScalaVersion.scala
plugin/src/main/scala/io/github/davidgregory084/ScalacOptions.scala

Added in 2.13.9: https://github.com/scala/scala/pull/9893

Add -Wnonunit-statement

---

plugin/src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
plugin/src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt
plugin/src/sbt-test/sbt-tpolecat/scalacOptions/project/OtherPlugin.scala
plugin/src/sbt-test/sbt-tpolecat/scalacOptions/test

We now maintain a set of `ScalacOptions` "managed" by sbt-tpolecat. When computing `scalacOptions`, we do not overwrite them, but instead we get the previous `scalacOptions.value` and we modify it.
We only remove options that are managed by sbt-tpolecat. And we only add options that are not already there (because they were already added in an upper delegate scope).
By default, we automatically compute the set of managed options as all the options that are "ever" added once by sbt-tpolecat in the delegate chain.

Fix #102: Do not overwrite other plugins' `scalacOptions`.

---

plugin/src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala
plugin/src/sbt-test/sbt-tpolecat/modeCommand/build.sbt
plugin/src/sbt-test/sbt-tpolecat/modeCommand/project/build.properties
plugin/src/sbt-test/sbt-tpolecat/modeCommand/project/plugins.sbt
plugin/src/sbt-test/sbt-tpolecat/modeCommand/test

Set mode in every scope

---

README.md
plugin/src/main/scala/io/github/davidgregory084/ScalaVersion.scala
plugin/src/main/scala/io/github/davidgregory084/ScalacOptions.scala
plugin/src/sbt-test/sbt-tpolecat/modePerConfiguration/build.sbt
plugin/src/sbt-test/sbt-tpolecat/scalacOptions/build.sbt

This PR prepares the plugin for the official scala 3.3.0 release (it is tagged, just not released quite yet https://github.com/lampepfl/dotty/releases/tag/3.3.0). It adds back all the warnings for unused and discarded values that is re-added in this release.

Add support for re-introduced warnings in scala 3.3.0

---

scalafix/input/src/main/scala/org/typelevel/fix/v0_5Tests.scala
scalafix/output/src/main/scala/org/typelevel/fix/v0_5Tests.scala
scalafix/rules/src/main/scala/fix/v0_5.scala

This PR updates the Scalafix migration for 0.5.x by handling some more possibilities that I didn't really think about, e.g.
```scala
import io.github.davidgregory084.ScalaVersion._
import io.github.davidgregory084.TpolecatPlugin._
import io.github.davidgregory084.TpolecatPlugin.autoImport.ScalacOptions._
```

Improve the 0.5.x migration by handling some more wildcard import possibilities

---

scalafix/input/src/main/scala/org/typelevel/fix/v0_5Tests.scala
scalafix/output/src/main/scala/org/typelevel/fix/v0_5Tests.scala
scalafix/rules/src/main/scala/fix/v0_5.scala

This is a bit of a weird edge case because I stupidly exported `ScalacOptions` as part of the `autoImport` object way back when I first added it to this plugin.

Improve the 0.5.x migration some more by handling `TpolecatPlugin.autoImport.ScalacOptions`

---

README.md

Hi!
Feel free to reject / amend this. I've added it because I've had to dig up that `ScalacOptions` import several times, and today I had to work out how to add several excludes at once. There may be a better way of course!

Update README to include import and Set examples

---

build.sbt
project/build.properties
project/plugins.sbt

I think the reason that #222 and #214 failed because the version mismatch between scala and scalafix, I'm not sure why tho 😄.
This also updates:
- scalafix 0.12.1
- sbt 1.10.1

Update scala 2.12.9

---

build.sbt
project/plugins.sbt

I learned in a discussion in the #scalafix discord channel  that is is possible to use the same version for Scalac than used by Scalafix itself: https://discord.com/channels/632642981228314653/632683673417678860/1288932888078975070
This is an alternative solution for: #237 
closes: #237 
closes: #236 
closes: #231

Sync the scalac version with the one used by scalafix
